[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'source ~/.config/nvim/rc/denite.rc.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']
hook_source = '''
    let g:neomru#file_mru_limit = 64
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'nabezokodaikon/denite-converter-basename_to_top'
on_source = ['denite.nvim']

# [[plugins]]	
# repo = 'Shougo/deoplete.nvim'
# on_event = 'InsertEnter'
# hook_source = 'source ~/.config/nvim/rc/deoplete.rc.vim'

# [[plugins]]
# repo = 'deoplete-plugins/deoplete-lsp'
# on_source = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_source = 'source ~/.config/nvim/rc/defx.rc.vim'

[[plugins]]
repo = 'kristijanhusak/defx-git'
on_source = ['defx.nvim']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [
    'html',
    'css',
    'scss'
    'javascript',
    'javascriptreact',
    'typescript',
    'typescriptreact',
]
hook_source = '''
    let g:user_emmet_install_global = 0
    let g:user_emmet_leader_key='<C-e>'
    augroup emmet_my_settings
        autocmd!
        autocmd FileType
        \ html,css,scss,javascript,javascriptreact,typescript,typescriptreact
        \ EmmetInstall
    augroup END
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = 'luafile ~/.config/nvim/lua/treesitter.lua'

# scala syntax
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

# rust configuration
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_command = 'rustfmt'
    let g:rustfmt_autosave = 1 
'''

[[plugins]]
repo = 'lepture/vim-velocity'
on_ft = 'velocity'

# Translate for Japanese/English
[[plugins]]
repo = 'nabezokodaikon/jaen-translate.vim'
on_cmd = [
    'TranslateJa2En',
    'TranslateEn2Ja'
]
