# プラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'

# テキストを囲ったり、囲いを外したりするプラグイン。
[[plugins]]
repo = 'tpope/vim-surround'

# コメントアウト
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# ユーザが自由にサブモードを定義できるプラグイン。
# タブ操作をカスタマイズするのに使用している。
[[plugins]]
repo = 'kana/vim-submode'

# カーソル移動を便利にする。
[[plugins]]
repo = 'easymotion/vim-easymotion'

# Color scheme
[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'hoob3rt/lualine.nvim'
