# プラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'

# テキストを囲ったり、囲いを外したりするプラグイン。
[[plugins]]
repo = 'tpope/vim-surround'

# コメントアウト
[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
    " コメントの間にスペースを開ける
    let NERDSpaceDelims = 1
    nnoremap co <Nop>
    vnoremap co <Nop>
    nmap co <Plug>NERDCommenterToggle
    vmap co <Plug>NERDCommenterToggle
'''

# ユーザが自由にサブモードを定義できるプラグイン。
# タブ操作をカスタマイズするのに使用している。
[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
    " Window resize.
    call submode#enter_with('window-resize', 'n', '', '<C-w>>', '<C-w>>')
    call submode#enter_with('window-resize', 'n', '', '<C-w><', '<C-w><')
    call submode#enter_with('window-resize', 'n', '', '<C-w>+', '<C-w>+')
    call submode#enter_with('window-resize', 'n', '', '<C-w>-', '<C-w>-')
    call submode#map('window-resize', 'n', '', '>', '<C-w>>')
    call submode#map('window-resize', 'n', '', '<', '<C-w><')
    call submode#map('window-resize', 'n', '', '+', '<C-w>+')
    call submode#map('window-resize', 'n', '', '-', '<C-w>-')

    " Tab change.
    call submode#enter_with('tab-next', 'n', '', 'gt', 'gt')
    call submode#map('tab-next', 'n', '', 't', 'gt')
    call submode#enter_with('tab-preview', 'n', '', 'gT', 'gT')
    call submode#map('tab-preview', 'n', '', 'T', 'gT')
'''

# カーソル移動を便利にする。
[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    " デフォルトのキーマッピングを無効化。
    let g:EasyMotion_do_mapping = 0
    " 検索後、Enterでカーソル位置に一番近いマッチした箇所に移動する。
    let g:EasyMotion_enter_jump_first = 1
    " 大文字、小文字を区別しない。
    let g:EasyMotion_smartcase = 1
    " キーワードの入力を2文字まで受け付ける。
    nmap <Leader>m <Plug>(easymotion-overwin-f2)
'''

# Color scheme
[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
    colorscheme gruvbox
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'hoob3rt/lualine.nvim'
hook_add = 'luafile ~/.config/nvim/lua/status-line.lua'

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
hook_add = 'luafile ~/.config/nvim/lua/completion.lua'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo = 'hrsh7th/cmp-path'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
