# Emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [
    'html',
    'css',
    'scss',
    'javascript',
    'javascriptreact',
    'typescript',
    'typescriptreact',
    'svelte',
]
hook_source = "lua require('plugins.emmet-vim')"

# LSP
[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufRead'
hook_source = "lua require('plugins.nvim-lspconfig')"

# Rust configuration
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = "lua require('plugins.rust')"

# VTL syntax
[[plugins]]
repo = 'lepture/vim-velocity'
on_ft = 'velocity'

# Treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
depends = [
    'Comment.nvim',
    'nvim-ts-context-commentstring'
]
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = "lua require('plugins.nvim-treesitter')"

[[plugins]]
repo = 'numToStr/Comment.nvim'

[[plugins]]
repo = 'JoosepAlviste/nvim-ts-context-commentstring'

# Translate
[[plugins]]
repo = 'nabezokodaikon/translate.nvim'
on_cmd = [
    'Translate'
]

# カーソル移動を便利にする。
[[plugins]]
repo = 'phaazon/hop.nvim'
on_cmd = 'HopWord'
hook_source = "lua require('plugins.hop')"

# Copy paste
[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-user'

