# テキストを囲ったり、囲いを外したりする。
[[plugins]]
repo = 'tpope/vim-surround'

# Comment out
[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = "lua require('plugins.nerdcommenter')"

# Color scheme
[[plugins]]
repo = 'ellisonleao/gruvbox.nvim'
hook_add = "lua require('plugins.gruvbox')"

# Status line
[[plugins]]
repo = 'hoob3rt/lualine.nvim'
hook_add = "lua require('plugins.lualine')"

# Tab line
[[plugins]]
repo = 'crispgm/nvim-tabline'
hook_add = "lua require('plugins.nvim-tabline')"

# Using Deno on plugin
[[plugins]]
repo = 'vim-denops/denops.vim'

