# denite.nvim
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = [
    'unite.vim',
    'neomru.vim',
    'neoyank.vim',
    'vim-gista-unite'
    ]
hook_source = '''
    source ~/.config/nvim/rc/plugins/denite.rc.vim
'''

# unite.vim
[[plugins]]
repo = 'Shougo/unite.vim'

# denite.nvimでファイル表示履歴を表示する。
[[plugins]]
repo = 'Shougo/neomru.vim'
hook_source = '''
    source ~/.config/nvim/rc/plugins/neomru.rc.vim
'''

# denite.vimでyankの履歴を表示する。
[[plugins]]
repo = 'Shougo/neoyank.vim'

# vim-gista と unite を連携させる。
[[plugins]]
repo = 'lambdalisue/vim-gista-unite'

# gist を使用する。
[[plugins]]
repo = 'lambdalisue/vim-gista'
on_cmd = 'Gista'
hook_source = '''
    source ~/.config/nvim/rc/plugins/vim-gista.rc.vim
'''

# 補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = '''
    source ~/.config/nvim/rc/plugins/deoplete.rc.vim
'''

# emmet-vim
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css', 'javascript']
hook_source = '''
    source ~/.config/nvim/rc/plugins/emmet-vim.rc.vim
'''

# Scala のシンタックスハイライト
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

# JSX Syntax
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'

# Syntax Highlighting and Indentation for Haskell and Cabal
[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'

# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
