# denite.nvim
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'source ~/.config/nvim/rc/plugins/denite.rc.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']
hook_source = '''
    let g:neomru#file_mru_limit = 64
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'nabezokodaikon/denite-converter-basename_to_top'
on_source = ['denite.nvim']

# deoplete.nvim
[[plugins]]	
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = 'source ~/.config/nvim/rc/plugins/deoplete.rc.vim'

[[plugins]]
repo = 'deoplete-plugins/deoplete-lsp'
on_source = ['deoplete.nvim']

# defx.nvim
[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_source = 'source ~/.config/nvim/rc/plugins/defx.rc.vim'

[[plugins]]
repo = 'kristijanhusak/defx-git'
on_source = ['defx.nvim']

# emmet-vim
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [
    'html',
    'javascript',
    'javascriptreact',
    'javascript.jsx'
    'typescript',
    'typescriptreact',
    'typescript.tsx'
    'vue',
]
hook_source = '''
    let g:user_emmet_install_global = 0
    let g:user_emmet_leader_key='<C-e>'
    augroup emmet-vim
        autocmd!
        autocmd FileType 
        \ html,
        \ javascript,javascriptreact,'javascript.jsx',
        \ typescript,typescriptreact,'typescript.tsx',
        \ vue,
        \ EmmetInstall
    augroup END
'''

# scala syntax
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# javascript syntax
[[plugins]]
repo = 'yuezk/vim-js'
on_source = ['vim-jsx-pretty']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_source = ['vim-jsx-pretty']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = [
    'javascript',
    'javascriptreact'
    'javascript.jsx',
    'typescript',
    'typescriptreact',
    'typescript.tsx'
]

# vue.js syntax
# [[plugins]]
# repo = 'posva/vim-vue'
# on_ft = 'vue'

# rust configuration
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_command = 'rustfmt'
    let g:rustfmt_autosave = 1 
'''

# graphql syntax
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = 'graphql'

# Translate for Japanese/English
[[plugins]]
repo = 'nabezokodaikon/jaen-translate.vim'
on_cmd = 'JaEnTranslate'
