# denite.nvim
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = ['neomru.vim', 'neoyank.vim']
hook_source = '''
    source ~/.config/nvim/rc/plugins/denite-lazy.rc.vim
'''

# unite.vim
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'
depends = ['vim-gista-unite', 'unite-outline', 'unite-tag']
hook_source = '''
    source ~/.config/nvim/rc/plugins/unite-lazy.rc.vim
'''

# denite.nvimでファイル表示履歴を表示する。
[[plugins]]
repo = 'Shougo/neomru.vim'

# denite.vimでyankの履歴を表示する。
[[plugins]]
repo = 'Shougo/neoyank.vim'

# vim-gista と unite を連携させる。
[[plugins]]
repo = 'lambdalisue/vim-gista-unite'

# unite-outline
[[plugins]]
repo = 'Shougo/unite-outline'

# unite-tag
[[plugins]]
repo = 'tsukkee/unite-tag'

# gist を使用する。
[[plugins]]
repo = 'lambdalisue/vim-gista'
on_cmd = 'Gista'
