# プラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'

# vimproc
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# 補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'

# emmet-vim
[[plugins]]
repo = 'mattn/emmet-vim'

# テキストを囲ったり、囲いを外したりするプラグイン。
[[plugins]]
repo = 'tpope/vim-surround'

# auto-ctags
[[plugins]]
repo = 'soramugi/auto-ctags.vim'

# コメントアウト
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# カラースキーム
[[plugins]]
repo = 'nanotech/jellybeans.vim'

# ユーザが自由にサブモードを定義できるプラグイン。
# タブ操作をカスタマイズするのに使用している。
[[plugins]]
repo = 'kana/vim-submode'

# タブごとにカレントディレクトリを切り替える。
[[plugins]]
repo = 'kana/vim-tabpagecd'

# git を操作する。
[[plugins]]
repo = 'tpope/vim-fugitive'

# カーソル移動を便利にする。
[[plugins]]
repo = 'easymotion/vim-easymotion'

# Scala のシンタックスハイライト
[[plugins]]
repo = 'derekwyatt/vim-scala'

# 編集ファイルの全体または一部を実行する。
[[plugins]]
repo = 'thinca/vim-quickrun'

# webapi-vim
[[plugins]]
repo = 'mattn/webapi-vim'
