# denite.nvim
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = [
    'unite.vim',
    'neomru.vim',
    'neoyank.vim',
    'vim-gista-unite',
    'unite-tag'
    ]
hook_source = '''
    source ~/.config/nvim/rc/plugins/denite.rc.vim
'''

# unite.vim
[[plugins]]
repo = 'Shougo/unite.vim'

# denite.nvimでファイル表示履歴を表示する。
[[plugins]]
repo = 'Shougo/neomru.vim'

# denite.vimでyankの履歴を表示する。
[[plugins]]
repo = 'Shougo/neoyank.vim'

# vim-gista と unite を連携させる。
[[plugins]]
repo = 'lambdalisue/vim-gista-unite'

# unite-tag
[[plugins]]
repo = 'tsukkee/unite-tag'

# gist を使用する。
[[plugins]]
repo = 'lambdalisue/vim-gista'
on_cmd = 'Gista'

# emmet-vim
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

# Scala のシンタックスハイライト
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

# JavaScript Syntax
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

# JSX Syntax
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
