# プラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'

# テキストを囲ったり、囲いを外したりするプラグイン。
[[plugins]]
repo = 'tpope/vim-surround'

# コメントアウト
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# ユーザが自由にサブモードを定義できるプラグイン。
# タブ操作をカスタマイズするのに使用している。
[[plugins]]
repo = 'kana/vim-submode'

# カーソル移動を便利にする。
[[plugins]]
repo = 'easymotion/vim-easymotion'

# 編集ファイルの全体または一部を実行する。
[[plugins]]
repo = 'thinca/vim-quickrun'

# Intellisense engine
[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'yarn install --frozen-lockfile'
on_event = 'InsertEnter'
hook_add = 'source ~/.config/nvim/rc/plugins/coc.rc.vim'

# Color scheme
[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
    let g:jellybeans_overrides = {
    \   'background': {
    \       'ctermbg': 'none',
    \       '256ctermbg': 'none'
    \   },
    \   'CursorLine': {
    \       '256ctermbg': '236'
    \   },
    \   'CursorColumn': {
    \       '256ctermbg': '236'
    \   },
    \   'Visual': {
    \       '256ctermbg': '238'
    \   },
    \   'PmenuSel': {
    \       'attr': 'bold'
    \   },
    \   'TabLineFill': {
    \       'attr': 'bold'
    \   },
    \   'TabLine': {
    \       'attr': 'bold'
    \   },
    \   'TabLineSel': {
    \       'attr': 'bold'
    \   },
    \   'StatusLine': {
    \       'attr': 'bold'
    \   },
    \   'StatusLineNC': {
    \       'attr': 'bold'
    \   }
    \}

    colorscheme jellybeans
'''
