# プラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neovim/nvim-lsp'	
hook_add = '''
    luafile ~/.config/nvim/lua/lsp.lua
    set signcolumn=yes
'''

[[plugins]]
repo = 'haorenW1025/diagnostic-nvim'

# テキストを囲ったり、囲いを外したりするプラグイン。
[[plugins]]
repo = 'tpope/vim-surround'

# コメントアウト
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# ユーザが自由にサブモードを定義できるプラグイン。
# タブ操作をカスタマイズするのに使用している。
[[plugins]]
repo = 'kana/vim-submode'

# カーソル移動を便利にする。
[[plugins]]
repo = 'easymotion/vim-easymotion'

# Git操作
[[plugins]]
repo = "tpope/vim-fugitive"

# Color scheme
[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
    let g:jellybeans_use_gui_italics=0
    let g:jellybeans_use_term_italics=0

    let g:jellybeans_overrides = {
    \   'background': {
    \       '256ctermbg': 'none'
    \   },
    \   'CursorLine': {
    \       '256ctermbg': '236'
    \   },
    \   'CursorColumn': {
    \       '256ctermbg': '236'
    \   },
    \   'Visual': {
    \       '256ctermbg': '238'
    \   },
    \   'PmenuSel': {
    \       'attr': 'bold'
    \   },
    \   'TabLineFill': {
    \       'attr': 'bold'
    \   },
    \   'TabLine': {
    \       'attr': 'bold'
    \   },
    \   'TabLineSel': {
    \       'attr': 'bold'
    \   }
    \}

    colorscheme jellybeans
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
    let g:airline_theme = 'angr'
'''
