# denite.nvim
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'source ~/.config/nvim/rc/plugins/denite.rc.vim'

# denite.nvimでファイル表示履歴を表示する。
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']
hook_source = '''
    let g:neomru#file_mru_limit = 64
'''

# denite.vimでyankの履歴を表示する。
[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = ['denite.nvim']

[[plugins]]
repo = 'nabezokodaikon/denite-converter-basename_to_top'
on_source = ['denite.nvim']

[[plugins]]	
repo = 'Shougo/deoplete.nvim'	
on_event = 'InsertEnter'	
hook_source = 'source ~/.config/nvim/rc/plugins/deoplete.rc.vim'	

[[plugins]]
repo = 'deoplete-plugins/deoplete-dictionary'	
on_source = ['deoplete.nvim']	

[[plugins]]
repo = 'deoplete-plugins/deoplete-tag'	
on_source = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/deoplete-lsp'
on_source = ['deoplete.nvim']

# File browser
[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = 'Defx'
hook_source = 'source ~/.config/nvim/rc/plugins/defx.rc.vim'

[[plugins]]
repo = 'kristijanhusak/defx-git'
on_source = ['defx.nvim']

[[plugins]]
repo = 'neovim/nvim-lsp'
hook_source = 'luafile ~/.config/nvim/lua/lsp.lua'
on_ft = [
    'javascript',
    'javascriptreact',
    'rust',
    'typescript',
]

# [[plugins]]
# repo = 'nvim-lua/completion-nvim'
# on_source = ['nvim-lsp']
# hook_source = '''
    # let g:completion_enable_auto_hover = 1
# '''

# [[plugins]]
# repo = 'nvim-lua/diagnostic-nvim'
# on_source = ['nvim-lsp']
# hook_source = '''
    # let g:diagnostic_enable_virtual_text = 1
# '''

# emmet-vim
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [
    'html',
    'css',
    'javascript',
    'javascript.jsx',
    'typescript',
    'typescript.tsx',
    'vue',
]
hook_source = '''
    let g:user_emmet_install_global = 0
    augroup emmet-vim
        autocmd!
        autocmd FileType html,css,javascript,javascript.jsx,typescript,typescript.tsx,vue EmmetInstall
    augroup END
'''

# Scala のシンタックスハイライト
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

# JSX Syntax
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'

# Syntax Highlighting and Indentation for Haskell and Cabal
[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'
hook_source = '''
    let g:haskell_indent_guard = 4
'''

# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# TypeScript syntax
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

# Vue.js syntax
[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

# Vim configuration for Rust.
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_command = 'rustfmt'
    let g:rustfmt_autosave = 1 
'''

[[plugins]]
repo = 'jdonaldson/vaxe'
on_ft = 'haxe'
hook_source = '''
    let g:vaxe_haxe_version = 3
'''

# Translate Japanese/English
[[plugins]]
repo = 'nabezokodaikon/jaen-translate.vim'
on_cmd = 'JaEnTranslate'
