# プラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'

# テキストを囲ったり、囲いを外したりするプラグイン。
[[plugins]]
repo = 'tpope/vim-surround'

# コメントアウト
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# ユーザが自由にサブモードを定義できるプラグイン。
# タブ操作をカスタマイズするのに使用している。
[[plugins]]
repo = 'kana/vim-submode'

# カーソル移動を便利にする。
[[plugins]]
repo = 'easymotion/vim-easymotion'

# Color scheme
[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
    let g:jellybeans_overrides = {
    \   'background': {
    \       '256ctermbg': 'none'
    \   },
    \   'CursorLine': {
    \       '256ctermbg': '236'
    \   },
    \   'CursorColumn': {
    \       '256ctermbg': '236'
    \   },
    \   'Visual': {
    \       '256ctermbg': '238'
    \   },
    \   'PmenuSel': {
    \       'attr': 'bold'
    \   },
    \   'TabLineFill': {
    \       'attr': 'bold'
    \   },
    \   'TabLine': {
    \       'attr': 'bold'
    \   },
    \   'TabLineSel': {
    \       'attr': 'bold'
    \   }
    \}

    colorscheme jellybeans
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
    let g:airline_theme = 'jellybeans'
'''
