# Emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [
    'html',
    'css',
    'scss'
    'javascript',
    'javascriptreact',
    'typescript',
    'typescriptreact',
]
hook_source = '''lua require('plugins.emmet-vim')'''

# Icon
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# Tree
[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
on_source = 'nvim-web-devicons'
on_cmd = 'NvimTreeToggle'
hook_source = '''lua require('plugins.nvim-tree')'''

# Outline
[[plugins]]
repo = 'simrat39/symbols-outline.nvim'
on_cmd = 'SymbolsOutline',
hook_source = '''lua require('plugins.symbols-outline')'''

# Completion
[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufRead'
hook_source = '''lua require('plugins.nvim-lspconfig')'''

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
on_event = 'VimEnter'
hook_source = '''lua require('plugins.nvim-cmp')'''

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
on_source = 'nvim-cmp'

# Fuzzy finder
[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = [
    'popup.nvim',
    'plenary.nvim',
]
on_cmd = 'Telescope'
hook_source = '''lua require('plugins.telescope')'''

# Rust configuration
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''lua require('plugins.rust')'''

# Scala syntax
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

# VTL syntax
[[plugins]]
repo = 'lepture/vim-velocity'
on_ft = 'velocity'

# Treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = '''lua require('plugins.nvim-treesitter')'''

# Translate
[[plugins]]
repo = 'nabezokodaikon/jaen-translate.vim'
on_cmd = [
    'TranslateJa2En',
    'TranslateEn2Ja'
]

# Fuzzy finder
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'
hook_source = 'source ~/.config/nvim/ddu.rc.vim'

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = 'ddu.vim'
on_cmd = 'Ddu'

[[plugins]]
repo = 'Shougo/ddu-ui-std'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'
