# Emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [
    'html',
    'css',
    'scss'
    'javascript',
    'javascriptreact',
    'typescript',
    'typescriptreact',
]
lua_source = '''
require('plugins.emmet-vim')
'''

# Icon
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# File Explorer
[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
depends = 'nvim-web-devicons'
on_cmd = 'NvimTreeToggle'
lua_source = '''
require('plugins.nvim-tree')
'''

# LSP
[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufRead'
lua_source = '''
require('plugins.nvim-lspconfig')
'''

# Fuzzy finder
[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = [
    'popup.nvim',
    'plenary.nvim',
    'nvim-web-devicons',
]
on_cmd = 'Telescope'
lua_source = '''
require('plugins.telescope')
'''

# Rust configuration
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
lua_source = '''
require('plugins.rust')
'''

# Scala syntax
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

# VTL syntax
[[plugins]]
repo = 'lepture/vim-velocity'
on_ft = 'velocity'

# Treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
lua_source = '''
require('plugins.nvim-treesitter')
'''

# Translate
[[plugins]]
repo = 'nabezokodaikon/jaen-translate.vim'
on_cmd = [
    'TranslateJa2En',
    'TranslateEn2Ja'
]

# カーソル移動を便利にする。
[[plugins]]
repo = 'phaazon/hop.nvim'
on_cmd = 'HopWord'
lua_source = '''
require('plugins.hop')
'''
