# Plugins manager
[[plugins]]
repo = 'Shougo/dein.vim'

# テキストを囲ったり、囲いを外したりする。
[[plugins]]
repo = 'tpope/vim-surround'

# Copy paste
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'

# Color scheme
[[plugins]]
repo = 'rktjmp/lush.nvim'

[[plugins]]
repo = 'ellisonleao/gruvbox.nvim'
lua_add = '''
require('plugins.gruvbox')
'''

# Status line
[[plugins]]
repo = 'hoob3rt/lualine.nvim'
lua_add = '''
require('plugins.lualine')
'''

# Tab line
[[plugins]]
repo = 'crispgm/nvim-tabline'
lua_add = '''
require('plugins.nvim-tabline')
'''
