# Emmet
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [
    'html',
    'css',
    'scss'
    'javascript',
    'javascriptreact',
    'typescript',
    'typescriptreact',
]
hook_source = '''lua require('plugins.emmet-vim')'''

# LSP
[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufRead'
hook_source = '''lua require('plugins.nvim-lspconfig')'''

# Rust configuration
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''lua require('plugins.rust')'''

# Scala syntax
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

# VTL syntax
[[plugins]]
repo = 'lepture/vim-velocity'
on_ft = 'velocity'

# Treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = '''lua require('plugins.nvim-treesitter')'''

# Translate
[[plugins]]
repo = 'nabezokodaikon/jaen-translate.vim'
on_cmd = [
    'TranslateJa2En',
    'TranslateEn2Ja'
]

# カーソル移動を便利にする。
[[plugins]]
repo = 'phaazon/hop.nvim'
on_cmd = 'HopWord'
hook_source = '''lua require('plugins.hop')'''

# Using Deno on plugin
[[plugins]]
repo = 'vim-denops/denops.vim'
