[[plugins]]
repo = 'hrsh7th/nvim-cmp'
on_event = 'VimEnter'
hook_source = '''lua require('plugins.nvim-cmp')'''

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'L3MON4D3/LuaSnip'
on_source = 'nvim-cmp'
